In [1]:
import pandas as pd

In [14]:
game_skater_stats = "hockey_data/game_skater_stats.csv"
game = "hockey_data/game.csv"
game_goals = "hockey_data/game_goals.csv"

# Import the books.csv file as a DataFrame
game_skater_stats_df = pd.read_csv(game_skater_stats, encoding="utf-8")
game_df = pd.read_csv(game)
game_goals_df = pd.read_csv(game_goals)

/Users/brianmclane/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (2) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [15]:
game_skater_stats_df

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
0,2016020045,8468513,4,955,1,0,0,2.0,0,0,...,0,1.0,1.0,0,0,1.0,1,858,97,0
1,2016020045,8476906,4,1396,1,0,4,2.0,0,0,...,0,1.0,2.0,0,0,2.0,0,1177,0,219
2,2016020045,8474668,4,915,0,0,1,1.0,0,0,...,0,2.0,0.0,0,0,0.0,-1,805,0,110
3,2016020045,8473512,4,1367,3,0,0,0.0,0,2,...,27,0.0,0.0,0,0,0.0,-1,1083,19,265
4,2016020045,8471762,4,676,0,0,3,2.0,0,0,...,0,0.0,1.0,0,0,0.0,-1,613,63,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945825,2018030417,8475807,6,501,0,0,1,2.0,0,0,...,0,0.0,0.0,0,0,0.0,-1,501,0,0
945826,2018030417,8475149,6,1062,0,0,2,0.0,0,0,...,1,1.0,0.0,0,0,0.0,-1,957,0,105
945827,2018030417,8475745,6,913,0,0,2,3.0,0,0,...,11,1.0,0.0,0,0,0.0,0,913,0,0
945828,2018030417,8478443,6,1006,0,0,1,1.0,0,0,...,0,0.0,1.0,0,0,2.0,-1,1006,0,0
945829,2018030417,8478046,6,909,0,0,2,0.0,0,0,...,0,1.0,1.0,0,0,0.0,0,909,0,0

In [18]:
game_goals_df

               play_id    strength gameWinningGoal emptyNet
0         2016020045_6        Even           False    False
1        2016020045_97        Even           False    False
2       2016020045_103  Power Play           False    False
3       2016020045_140  Power Play           False    False
4       2016020045_197  Power Play           False    False
...                ...         ...             ...      ...
148987   2018030417_81        Even           False    False
148988  2018030417_100        Even            True    False
148989  2018030417_257        Even           False    False
148990  2018030417_277        Even           False    False
148991  2018030417_290        Even           False    False

[148992 rows x 4 columns]

In [19]:
game_goals_df.dropna()

               play_id    strength gameWinningGoal emptyNet
0         2016020045_6        Even           False    False
1        2016020045_97        Even           False    False
2       2016020045_103  Power Play           False    False
3       2016020045_140  Power Play           False    False
4       2016020045_197  Power Play           False    False
...                ...         ...             ...      ...
148987   2018030417_81        Even           False    False
148988  2018030417_100        Even            True    False
148989  2018030417_257        Even           False    False
148990  2018030417_277        Even           False    False
148991  2018030417_290        Even           False    False

[143949 rows x 4 columns]