In [1]:
import pandas as pd
import numpy as np

In [2]:
game_skater_stats = "hockey_data/game_skater_stats.csv"
game_goalie_stats = "hockey_data/game_goalie_stats.csv"
player_info = "hockey_data/player_info.csv"

In [3]:
# Import the books.csv file as a DataFrame
game_skater_stats_df = pd.read_csv(game_skater_stats, encoding="utf-8")
game_goalie_stats_df = pd.read_csv(game_goalie_stats)
player_info_df = pd.read_csv(player_info)

In [4]:
game_skater_stats_df

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
0,2016020045,8468513,4,955,1,0,0,2.0,0,0,...,0,1.0,1.0,0,0,1.0,1,858,97,0
1,2016020045,8476906,4,1396,1,0,4,2.0,0,0,...,0,1.0,2.0,0,0,2.0,0,1177,0,219
2,2016020045,8474668,4,915,0,0,1,1.0,0,0,...,0,2.0,0.0,0,0,0.0,-1,805,0,110
3,2016020045,8473512,4,1367,3,0,0,0.0,0,2,...,27,0.0,0.0,0,0,0.0,-1,1083,19,265
4,2016020045,8471762,4,676,0,0,3,2.0,0,0,...,0,0.0,1.0,0,0,0.0,-1,613,63,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945825,2018030417,8475807,6,501,0,0,1,2.0,0,0,...,0,0.0,0.0,0,0,0.0,-1,501,0,0
945826,2018030417,8475149,6,1062,0,0,2,0.0,0,0,...,1,1.0,0.0,0,0,0.0,-1,957,0,105
945827,2018030417,8475745,6,913,0,0,2,3.0,0,0,...,11,1.0,0.0,0,0,0.0,0,913,0,0
945828,2018030417,8478443,6,1006,0,0,1,1.0,0,0,...,0,0.0,1.0,0,0,2.0,-1,1006,0,0
945829,2018030417,8478046,6,909,0,0,2,0.0,0,0,...,0,1.0,1.0,0,0,0.0,0,909,0,0

In [5]:
game_skater_stats_df.dropna()

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
0,2016020045,8468513,4,955,1,0,0,2.0,0,0,...,0,1.0,1.0,0,0,1.0,1,858,97,0
1,2016020045,8476906,4,1396,1,0,4,2.0,0,0,...,0,1.0,2.0,0,0,2.0,0,1177,0,219
2,2016020045,8474668,4,915,0,0,1,1.0,0,0,...,0,2.0,0.0,0,0,0.0,-1,805,0,110
3,2016020045,8473512,4,1367,3,0,0,0.0,0,2,...,27,0.0,0.0,0,0,0.0,-1,1083,19,265
4,2016020045,8471762,4,676,0,0,3,2.0,0,0,...,0,0.0,1.0,0,0,0.0,-1,613,63,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945825,2018030417,8475807,6,501,0,0,1,2.0,0,0,...,0,0.0,0.0,0,0,0.0,-1,501,0,0
945826,2018030417,8475149,6,1062,0,0,2,0.0,0,0,...,1,1.0,0.0,0,0,0.0,-1,957,0,105
945827,2018030417,8475745,6,913,0,0,2,3.0,0,0,...,11,1.0,0.0,0,0,0.0,0,913,0,0
945828,2018030417,8478443,6,1006,0,0,1,1.0,0,0,...,0,0.0,1.0,0,0,2.0,-1,1006,0,0
945829,2018030417,8478046,6,909,0,0,2,0.0,0,0,...,0,1.0,1.0,0,0,0.0,0,909,0,0

In [6]:
player_info_df

,player_id,firstName,lastName,nationality,birthCity,primaryPosition,birthDate,birthStateProvince,height,height_cm,weight,shootsCatches
0,8466148,Marian,Hossa,SVK,Stará Lubovna,RW,1979-01-12 00:00:00,NaN,"6' 1""",185.42,207.0,L
1,8465058,Michal,Rozsival,CZE,Vlasim,D,1978-09-03 01:00:00,NaN,"6' 1""",185.42,210.0,R
2,8476906,Shayne,Gostisbehere,USA,Pembroke Pines,D,1993-04-20 01:00:00,FL,"5' 11""",180.34,180.0,L
3,8466285,Brian,Campbell,CAN,Strathroy,D,1979-05-23 01:00:00,ON,"5' 10""",177.80,192.0,L
4,8470607,Brent,Seabrook,CAN,Richmond,D,1985-04-20 01:00:00,BC,"6' 3""",190.50,220.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...
3920,8479374,Adam,Mascherin,CAN,Maple,LW,1998-06-06 01:00:00,ON,"5' 10""",177.80,205.0,L
3921,8479403,Tyler,Parsons,USA,Mt. Clemas,G,1997-09-18 01:00:00,MI,"6' 1""",185.42,185.0,L
3922,8480970,Marcus,Hogstrom,SWE,Sveg,D,1989-03-20 00:00:00,NaN,"6' 4""",193.04,200.0,L
3923,8477574,Parker,Milner,USA,Pittsburgh,G,1990-09-06 01:00:00,PA,"6' 1""",185.42,185.0,L
3924,8477352,Ryan,Fitzgerald,USA,Boca Raton,C,1994-10-19 01:00:00,FL,"5' 9""",175.26,172.0,R

In [7]:
game_skater_stats_df.dtypes

game_id                   int64
player_id                 int64
team_id                   int64
timeOnIce                 int64
assists                   int64
goals                     int64
shots                     int64
hits                    float64
powerPlayGoals            int64
powerPlayAssists          int64
penaltyMinutes            int64
faceOffWins               int64
faceoffTaken              int64
takeaways               float64
giveaways               float64
shortHandedGoals          int64
shortHandedAssists        int64
blocked                 float64
plusMinus                 int64
evenTimeOnIce             int64
shortHandedTimeOnIce      int64
powerPlayTimeOnIce        int64
dtype: object

In [8]:
game_skater_stats_df = game_skater_stats_df.loc[game_skater_stats_df['team_id'] == 16]
game_skater_stats_df

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
18,2016020045,8466148,16,723,0,1,2,0.0,1,0,...,0,0.0,0.0,0,0,1.0,0,499,128,96
19,2016020045,8471769,16,1241,0,0,1,0.0,0,0,...,0,0.0,2.0,0,0,1.0,0,1010,224,7
20,2016020045,8477929,16,652,0,1,1,0.0,0,0,...,0,2.0,1.0,0,0,1.0,1,547,105,0
21,2016020045,8466285,16,1068,1,0,0,1.0,0,1,...,0,0.0,2.0,0,0,0.0,1,972,0,96
22,2016020045,8470607,16,1294,3,0,0,2.0,0,1,...,0,0.0,3.0,0,0,1.0,2,1030,114,150
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
939363,2018021266,8479465,16,850,0,1,2,0.0,0,0,...,1,0.0,0.0,0,0,0.0,1,791,59,0
939364,2018021266,8473573,16,1175,0,0,4,0.0,0,0,...,10,3.0,0.0,0,0,0.0,-1,1000,125,50
939365,2018021266,8478440,16,969,1,0,5,0.0,0,0,...,9,1.0,0.0,0,0,0.0,-1,779,0,190
939366,2018021266,8478055,16,1048,0,0,0,0.0,0,0,...,0,2.0,0.0,0,0,1.0,0,910,138,0
939367,2018021266,8476473,16,1010,0,0,2,1.0,0,0,...,0,0.0,0.0,0,0,3.0,0,872,138,0

In [9]:
game_goalie_stats_df = game_goalie_stats_df.loc[game_goalie_stats_df['team_id'] == 16]
game_goalie_stats_df

,game_id,player_id,team_id,timeOnIce,assists,goals,pim,shots,saves,powerPlaySaves,shortHandedSaves,evenSaves,shortHandedShotsAgainst,evenShotsAgainst,powerPlayShotsAgainst,decision,savePercentage,powerPlaySavePercentage,evenStrengthSavePercentage
2,2016020045,8470645,16,3598,0,0,0,27,23,2,0,21,0,23,4,W,85.185185,50.000000,91.304348
32,2016020107,8470645,16,3608,0,0,0,32,30,4,0,26,0,27,5,W,93.750000,80.000000,96.296296
179,2017021255,8475234,16,3496,0,0,0,34,31,4,0,27,0,30,4,L,91.176471,100.000000,90.000000
189,2017021010,8475234,16,1640,0,0,0,10,8,0,0,8,0,10,0,NaN,80.000000,NaN,80.000000
190,2017021010,8476341,16,1823,0,0,0,21,17,0,1,16,1,19,1,L,80.952381,0.000000,84.210526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56220,2018021255,8470645,16,1546,0,0,0,9,9,0,0,9,0,9,0,NaN,100.000000,NaN,100.000000
56226,2018021255,8470320,16,1993,0,0,0,26,25,1,0,24,0,24,2,W,96.153846,50.000000,100.000000
56227,2018021255,8470645,16,1546,0,0,0,9,9,0,0,9,0,9,0,NaN,100.000000,NaN,100.000000
56250,2018021266,8470320,16,3582,0,0,0,49,45,5,1,39,1,42,6,L,91.836735,83.333333,92.857143
56282,2018021266,8470320,16,3582,0,0,0,49,45,5,1,39,1,42,6,L,91.836735,83.333333,92.857143

In [10]:
player_list = game_skater_stats_df["player_id"].unique()
player_list = list(player_list)
len(player_list)

280

In [11]:
goalie_id = game_goalie_stats_df["player_id"].unique()
goalie_id = list(goalie_id)
len(goalie_id)

29

In [12]:
player_list.extend(goalie_id)
len(player_list)

309

In [15]:
boolean_series = player_info_df.player_id.isin(player_list) 

filtered_df = player_info_df[boolean_series]
filtered_df

,player_id,firstName,lastName,nationality,birthCity,primaryPosition,birthDate,birthStateProvince,height,height_cm,weight,shootsCatches
0,8466148,Marian,Hossa,SVK,Stará Lubovna,RW,1979-01-12 00:00:00,NaN,"6' 1""",185.42,207.0,L
1,8465058,Michal,Rozsival,CZE,Vlasim,D,1978-09-03 01:00:00,NaN,"6' 1""",185.42,210.0,R
3,8466285,Brian,Campbell,CAN,Strathroy,D,1979-05-23 01:00:00,ON,"5' 10""",177.80,192.0,L
4,8470607,Brent,Seabrook,CAN,Richmond,D,1985-04-20 01:00:00,BC,"6' 3""",190.50,220.0,R
5,8474668,Dale,Weise,CAN,Winnipeg,RW,1988-08-05 01:00:00,MB,"6' 2""",187.96,206.0,R
...,...,...,...,...,...,...,...,...,...,...,...,...
3809,8479542,Brandon,Hagel,CAN,Saskatoon,LW,1998-08-27 01:00:00,SK,"5' 11""",180.34,174.0,L
3833,8479523,Lucas,Carlsson,SWE,Gävle,D,1997-07-05 01:00:00,NaN,"6' 0""",182.88,189.0,L
3839,8480814,Nicolas,Beaudin,CAN,Chateauguay,D,1999-10-07 01:00:00,QC,"5' 11""",180.34,168.0,L
3893,8479657,Alexandre,Fortin,CAN,Blainville,LW,1997-02-25 00:00:00,QC,"6' 0""",182.88,184.0,L
3903,8480954,Jacob,Nilsson,SWE,Morrum,C,1993-10-12 01:00:00,NaN,"5' 10""",177.80,180.0,L