In [1]:
import pandas as pd
import numpy as np

In [2]:
game_skater_stats = "hockey_data/game_skater_stats.csv"
game_goalie_stats = "hockey_data/game_goalie_stats.csv"
player_info = "hockey_data/player_info.csv"

In [3]:
game_skater_stats_df = pd.read_csv(game_skater_stats, encoding="utf-8")
game_goalie_stats_df = pd.read_csv(game_goalie_stats)
player_info_df = pd.read_csv(player_info)

In [4]:
game_skater_stats_df.dropna()

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
0,2016020045,8468513,4,955,1,0,0,2.0,0,0,...,0,1.0,1.0,0,0,1.0,1,858,97,0
1,2016020045,8476906,4,1396,1,0,4,2.0,0,0,...,0,1.0,2.0,0,0,2.0,0,1177,0,219
2,2016020045,8474668,4,915,0,0,1,1.0,0,0,...,0,2.0,0.0,0,0,0.0,-1,805,0,110
3,2016020045,8473512,4,1367,3,0,0,0.0,0,2,...,27,0.0,0.0,0,0,0.0,-1,1083,19,265
4,2016020045,8471762,4,676,0,0,3,2.0,0,0,...,0,0.0,1.0,0,0,0.0,-1,613,63,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945825,2018030417,8475807,6,501,0,0,1,2.0,0,0,...,0,0.0,0.0,0,0,0.0,-1,501,0,0
945826,2018030417,8475149,6,1062,0,0,2,0.0,0,0,...,1,1.0,0.0,0,0,0.0,-1,957,0,105
945827,2018030417,8475745,6,913,0,0,2,3.0,0,0,...,11,1.0,0.0,0,0,0.0,0,913,0,0
945828,2018030417,8478443,6,1006,0,0,1,1.0,0,0,...,0,0.0,1.0,0,0,2.0,-1,1006,0,0
945829,2018030417,8478046,6,909,0,0,2,0.0,0,0,...,0,1.0,1.0,0,0,0.0,0,909,0,0

In [8]:
playerPos_df = player_info_df[['player_id', 'primaryPosition']]
playerPos_df

      player_id primaryPosition
0       8466148              RW
1       8465058               D
2       8476906               D
3       8466285               D
4       8470607               D
...         ...             ...
3920    8479374              LW
3921    8479403               G
3922    8480970               D
3923    8477574               G
3924    8477352               C

[3925 rows x 2 columns]

In [11]:
merged_df = game_skater_stats_df.merge(playerPos_df, how="inner", on="player_id")
merged_df.drop_duplicates(inplace=True)
merged_df

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce,primaryPosition
0,2016020045,8468513,4,955,1,0,0,2.0,0,0,...,1.0,1.0,0,0,1.0,1,858,97,0,D
1,2015020906,8468513,4,1148,0,0,1,0.0,0,0,...,0.0,0.0,0,0,4.0,0,1069,79,0,D
2,2016020070,8468513,4,1184,1,0,1,1.0,0,0,...,0.0,1.0,0,0,5.0,-1,995,189,0,D
3,2015020007,8468513,4,1096,0,0,0,1.0,0,0,...,0.0,0.0,0,0,3.0,-1,1002,94,0,D
4,2016020759,8468513,4,816,0,0,1,0.0,0,0,...,0.0,0.0,0,0,1.0,1,816,0,0,D
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945820,2018021245,8477865,17,906,0,0,1,2.0,0,0,...,0.0,0.0,0,0,0.0,0,876,30,0,D
945822,2018021261,8477865,17,949,0,0,2,0.0,0,0,...,0.0,2.0,0,0,2.0,-1,949,0,0,D
945824,2018021249,8481479,23,723,0,0,1,0.0,0,0,...,1.0,1.0,0,0,0.0,-1,723,0,0,D
945826,2018021258,8481479,23,879,0,0,2,0.0,0,0,...,0.0,0.0,0,0,2.0,0,879,0,0,D
945828,2018021270,8481486,54,1263,1,0,1,0.0,0,0,...,0.0,1.0,0,0,1.0,-1,1152,2,109,D

In [12]:
game = "hockey_data/game.csv"
game_df = pd.read_csv(game, encoding="utf-8")

In [14]:
game_df = game_df[['game_id', 'season', 'date_time_GMT']].drop_duplicates()

In [16]:
merged2 = merged_df.merge(game_df, how="inner", on="game_id")
merged2

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce,primaryPosition,season,date_time_GMT
0,2016020045,8468513,4,955,1,0,0,2.0,0,0,...,0,0,1.0,1,858,97,0,D,20162017,2016-10-19T00:30:00Z
1,2016020045,8476906,4,1396,1,0,4,2.0,0,0,...,0,0,2.0,0,1177,0,219,D,20162017,2016-10-19T00:30:00Z
2,2016020045,8474668,4,915,0,0,1,1.0,0,0,...,0,0,0.0,-1,805,0,110,RW,20162017,2016-10-19T00:30:00Z
3,2016020045,8473512,4,1367,3,0,0,0.0,0,2,...,0,0,0.0,-1,1083,19,265,C,20162017,2016-10-19T00:30:00Z
4,2016020045,8471762,4,676,0,0,3,2.0,0,0,...,0,0,0.0,-1,613,63,0,C,20162017,2016-10-19T00:30:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853399,2000021114,8457646,12,908,0,0,2,NaN,0,0,...,0,0,NaN,-1,860,48,0,LW,20002001,2001-03-25T00:00:00Z
853400,2000021114,8445176,7,973,1,0,2,NaN,0,0,...,0,0,NaN,1,836,6,131,RW,20002001,2001-03-25T00:00:00Z
853401,2000021114,8467418,12,925,0,0,0,NaN,0,0,...,0,0,NaN,-1,842,83,0,LW,20002001,2001-03-25T00:00:00Z
853402,2000021114,8462085,12,926,0,0,2,NaN,0,0,...,0,0,NaN,0,850,0,76,RW,20002001,2001-03-25T00:00:00Z
853403,2000021114,8447680,12,1437,0,0,1,NaN,0,0,...,0,0,NaN,-2,1139,215,83,D,20002001,2001-03-25T00:00:00Z

In [20]:
groupTest = merged2.groupby(['game_id', 'team_id', 'primaryPosition'])[['timeOnIce', 'assists', 'goals', 'shots', 'hits', 'powerPlayGoals', 'powerPlayAssists', 'penaltyMinutes', 'faceOffWins', 'takeaways', 'giveaways', 'shortHandedGoals', 'shortHandedAssists', 'blocked', 'evenTimeOnIce', 'shortHandedTimeOnIce', 'powerPlayTimeOnIce']].sum()
groupTest

                                    timeOnIce  assists  goals  shots  hits  \
game_id    team_id primaryPosition
2000020001 21      C                     5677        3      0      9   0.0
                   D                     7221        0      0     11   0.0
                   LW                    2364        0      1      5   0.0
                   RW                    2989        1      1      3   0.0
           25      C                     2661        1      1      5   0.0
...                                       ...      ...    ...    ...   ...
2019040653 87      LW                    1474        3      2      5   0.0
                   RW                     442        1      1      2   0.0
           90      C                     2070        3      4     13   0.0
                   D                      765        3      0      3   0.0
                   LW                     765        2      1      4   0.0

                                    powerPlayGoals  powerPlayAssists  \
game_id    team_id primaryPosition
2000020001 21      C                             0                 2
                   D                             0                 0
                   LW                            0                 0
                   RW                            1                 0
           25      C                             1                 0
...                                            ...               ...
2019040653 87      LW                            0                 0
                   RW                            0                 0
           90      C                             0                 0
                   D                             0                 0
                   LW                            0                 0

                                    penaltyMinutes  faceOffWins  takeaways  \
game_id    team_id primaryPosition
2000020001 21      C                            10           36        0.0
                   D                             6            0        0.0
                   LW                            2            1        0.0
                   RW                            0            1        0.0
           25      C                             0           30        0.0
...                                            ...          ...        ...
2019040653 87      LW                            0            5        2.0
                   RW                            0            0        0.0
           90      C                             0           10        4.0
                   D                             0            0        1.0
                   LW                            0            0        1.0

                                    giveaways  shortHandedGoals  \
game_id    team_id primaryPosition
2000020001 21      C                      0.0                 0
                   D                      0.0                 0
                   LW                     0.0                 0
                   RW                     0.0                 0
           25      C                      0.0                 0
...                                       ...               ...
2019040653 87      LW                     1.0                 0
                   RW                     0.0                 0
           90      C                      1.0                 0
                   D                      0.0                 0
                   LW                     0.0                 0

                                    shortHandedAssists  blocked  \
game_id    team_id primaryPosition
2000020001 21      C                                 0      0.0
                   D                                 0      0.0
                   LW                                0      0.0
                   RW                                0      0.0
           25      C                                 0      0.0
...                                                ...      ...
2019040653 87      LW                                0      1.0
                   RW                                0      0.0
           90      C                                 0      1.0
                   D                                 0      1.0
                   LW                                0      0.0

                                    evenTimeOnIce  shortHandedTimeOnIce  \
game_id    team_id primaryPosition
2000020001 21      C                         2730                   819
                   D                         4384                  1490
                   LW                        1486                   569
                   RW                        1905                   177
           25      C                         1319                   498
...                                           ...                   ...
2019040653 87      LW                        1474                     0
                   RW                         442                     0
           90      C                         2070                     0
                   D                          765                     0
                   LW                         765                     0

                                    powerPlayTimeOnIce
game_id    team_id primaryPosition
2000020001 21      C                              2128
                   D                              1347
                   LW                              309
                   RW                              907
           25      C                               844
...                                                ...
2019040653 87      LW                                0
                   RW                                0
           90      C                                 0
                   D                                 0
                   LW                                0

[189258 rows x 17 columns]

In [21]:
pwd

'C:\\Users\\cande\\Desktop\\hockey-challenge'